sonar.projectKey=digitalia-sourcing-frontend
sonar.projectName=Digitalia Sourcing Frontend
sonar.organization=salmaskit

sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.js,src/__tests__/**/*.test.jsx,src/__tests__/**/*.spec.js,src/__tests__/**/*.spec.jsx
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,dist/**,coverage/**,public/**,src/test/**,src/__tests__/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/test/**,src/__tests__/**,src/main.jsx
