"""
Mock profile database for development and fallback.
"""
MOCK_PROFILES: list[dict] = [
    {
        "id": "mock-001",
        "full_name": "Alexandre Dupont",
        "headline": "Senior Java & Spring Boot Engineer | Microservices | AWS",
        "location": "Paris, France",
        "current_company": "BNP Paribas Digital",
        "current_role": "Lead Backend Engineer",
        "experience_years": 8,
        "education": "Master Informatique — Université Paris-Saclay (2016)",
        "skills": ["Java", "Spring Boot", "Spring Security", "Microservices", "Docker",
                   "Kubernetes", "AWS", "PostgreSQL", "Kafka", "REST APIs", "JUnit 5", "Maven"],
        "seniority": "Senior",
        "linkedin_url": "linkedin.com/in/alexandre-dupont-dev",
        "email": "a.dupont@email.fr",
        "avatar_url": "https://randomuser.me/api/portraits/men/32.jpg",
        "summary": "8 ans d'expérience en développement Java entreprise. Spécialisé dans les architectures microservices haute disponibilité et les systèmes bancaires critiques. Maîtrise de Spring Boot, Kubernetes et AWS.",
        "availability": "Disponible sous 3 mois",
        "salary_expectation": "65 000–75 000 € / an",
        "contract_preference": "CDI",
        "languages": ["Français", "Anglais"],
        "source": "mock",
    },
    {
        "id": "mock-002",
        "full_name": "Fatima Benali",
        "headline": "Full-Stack Developer | React + Java | 5 ans XP | Paris/Remote",
        "location": "Île-de-France, France",
        "current_company": "Thales Digital Solutions",
        "current_role": "Software Engineer",
        "experience_years": 5,
        "education": "Diplôme d'Ingénieur — CentraleSupélec (2019)",
        "skills": ["Java", "Spring Boot", "React", "TypeScript", "PostgreSQL",
                   "Docker", "CI/CD", "GitLab CI", "REST APIs", "TDD"],
        "seniority": "Mid",
        "linkedin_url": "linkedin.com/in/fatima-benali-fullstack",
        "email": "f.benali@email.fr",
        "avatar_url": "https://randomuser.me/api/portraits/women/44.jpg",
        "summary": "Développeuse Full-Stack polyvalente, à l'aise aussi bien côté backend (Java/Spring) que frontend (React/TS). Habituée aux environnements Agile et CI/CD.",
        "availability": "Immédiate",
        "salary_expectation": "52 000–60 000 € / an",
        "contract_preference": "CDI",
        "languages": ["Français", "Anglais", "Arabe"],
        "source": "mock",
    },
    {
        "id": "mock-003",
        "full_name": "Thomas Leclerc",
        "headline": "Cloud & DevOps Engineer | Kubernetes | Terraform | Azure/AWS",
        "location": "Lyon, France",
        "current_company": "Capgemini Engineering",
        "current_role": "Senior DevOps Architect",
        "experience_years": 9,
        "education": "Ingénieur — INSA Lyon (2015)",
        "skills": ["Kubernetes", "Docker", "Terraform", "AWS", "Azure", "CI/CD",
                   "Jenkins", "Ansible", "Python", "Bash", "Prometheus", "Grafana"],
        "seniority": "Senior",
        "linkedin_url": "linkedin.com/in/thomas-leclerc-devops",
        "email": "t.leclerc@email.fr",
        "avatar_url": "https://randomuser.me/api/portraits/men/55.jpg",
        "summary": "Expert DevOps avec 9 ans d'expérience sur des projets complexes. Fort sur l'IaC (Terraform), l'observabilité et l'automatisation CI/CD. Certifié AWS Solutions Architect et CKA.",
        "availability": "Disponible sous 1 mois",
        "salary_expectation": "70 000–80 000 € / an",
        "contract_preference": "CDI ou Freelance",
        "languages": ["Français", "Anglais"],
        "source": "mock",
    },
    {
        "id": "mock-004",
        "full_name": "Yasmine Ouertatani",
        "headline": "Data Engineer | Python · Spark · Airflow | Big Data · MLOps",
        "location": "Toulouse, France",
        "current_company": "Airbus Digital",
        "current_role": "Data Engineer",
        "experience_years": 4,
        "education": "Master Data Science — Université Toulouse III (2020)",
        "skills": ["Python", "Apache Spark", "Apache Airflow", "SQL", "PostgreSQL",
                   "AWS S3", "Redshift", "dbt", "Pandas", "Scikit-learn", "Docker"],
        "seniority": "Mid",
        "linkedin_url": "linkedin.com/in/yasmine-ouertatani-data",
        "email": "y.ouertatani@email.fr",
        "avatar_url": "https://randomuser.me/api/portraits/women/23.jpg",
        "summary": "Data Engineer spécialisée dans les pipelines de données à grande échelle. Expérience dans les industries aérospatiale et industrielle. Solides bases en machine learning et MLOps.",
        "availability": "Disponible sous 2 mois",
        "salary_expectation": "50 000–58 000 € / an",
        "contract_preference": "CDI",
        "languages": ["Français", "Anglais", "Arabe"],
        "source": "mock",
    },
    {
        "id": "mock-005",
        "full_name": "Nicolas Renard",
        "headline": "Tech Lead Java/Spring | Architecture Microservices | 12 ans XP",
        "location": "Paris, France",
        "current_company": "Société Générale — SGTI",
        "current_role": "Principal Software Architect",
        "experience_years": 12,
        "education": "Ingénieur — École Polytechnique (2012)",
        "skills": ["Java", "Spring Boot", "Spring Cloud", "Microservices", "DDD",
                   "Event Sourcing", "CQRS", "Kafka", "Docker", "Kubernetes",
                   "Architecture", "Team Leadership", "Code Review"],
        "seniority": "Lead",
        "linkedin_url": "linkedin.com/in/nicolas-renard-architect",
        "email": "n.renard@email.fr",
        "avatar_url": "https://randomuser.me/api/portraits/men/71.jpg",
        "summary": "Architecte logiciel senior avec 12 ans d'expertise en Java d'entreprise. Spécialisé en DDD, Event Sourcing et architectures distribuées dans le secteur bancaire. Leadership technique d'équipes de 8-15 personnes.",
        "availability": "Disponible sous 3 mois",
        "salary_expectation": "85 000–95 000 € / an",
        "contract_preference": "CDI",
        "languages": ["Français", "Anglais"],
        "source": "mock",
    },
    {
        "id": "mock-006",
        "full_name": "Sofia Martins",
        "headline": "Frontend Engineer | React · TypeScript · Next.js | UI/UX Focus",
        "location": "Remote (Portugal, open to France)",
        "current_company": "Freelance",
        "current_role": "Senior Frontend Developer",
        "experience_years": 6,
        "education": "Licence Informatique — Universidade do Porto (2018)",
        "skills": ["React", "TypeScript", "Next.js", "TailwindCSS", "GraphQL",
                   "Jest", "Playwright", "Figma", "Accessibility (a11y)", "Performance"],
        "seniority": "Senior",
        "linkedin_url": "linkedin.com/in/sofia-martins-frontend",
        "email": "sofia.m@email.eu",
        "avatar_url": "https://randomuser.me/api/portraits/women/65.jpg",
        "summary": "Développeuse frontend passionnée par les interfaces performantes et accessibles. 6 ans en freelance pour des clients comme Doctolib, Orange et des startups fintech.",
        "availability": "Immédiate",
        "salary_expectation": "55 000–65 000 € / an",
        "contract_preference": "Freelance ou CDI",
        "languages": ["Portugais", "Anglais", "Français (B2)"],
        "source": "mock",
    },
    {
        "id": "mock-007",
        "full_name": "Karim Aïssa",
        "headline": "Machine Learning Engineer | NLP · LLMs · Python | Paris",
        "location": "Paris, France",
        "current_company": "Criteo AI Lab",
        "current_role": "ML Engineer",
        "experience_years": 5,
        "education": "Master IA — Sorbonne Université (2019)",
        "skills": ["Python", "PyTorch", "TensorFlow", "Transformers (HuggingFace)",
                   "LangChain", "LangGraph", "FastAPI", "Docker", "MLflow", "SQL"],
        "seniority": "Mid",
        "linkedin_url": "linkedin.com/in/karim-aissa-ml",
        "email": "k.aissa@email.fr",
        "avatar_url": "https://randomuser.me/api/portraits/men/28.jpg",
        "summary": "ML Engineer spécialisé en NLP et LLMs. Expérience en production de modèles de recommandation et de systèmes de génération de texte. Contributeur open-source HuggingFace.",
        "availability": "Disponible sous 2 mois",
        "salary_expectation": "58 000–68 000 € / an",
        "contract_preference": "CDI",
        "languages": ["Français", "Anglais", "Arabe"],
        "source": "mock",
    },
    {
        "id": "mock-008",
        "full_name": "Camille Forestier",
        "headline": "Junior Java Developer | Spring Boot · SQL | Alternance terminée",
        "location": "Bordeaux, France",
        "current_company": "Atos",
        "current_role": "Junior Software Developer",
        "experience_years": 2,
        "education": "Master MIAGE — Université de Bordeaux (2024)",
        "skills": ["Java", "Spring Boot", "SQL", "PostgreSQL", "Git",
                   "Maven", "JUnit", "REST APIs", "HTML/CSS"],
        "seniority": "Junior",
        "linkedin_url": "linkedin.com/in/camille-forestier-dev",
        "email": "c.forestier@email.fr",
        "avatar_url": "https://randomuser.me/api/portraits/women/12.jpg",
        "summary": "Développeuse junior motivée, diplômée en 2024. 2 ans d'alternance chez Atos sur des projets Java/Spring Boot. Recherche un poste CDI pour continuer à monter en compétences.",
        "availability": "Immédiate",
        "salary_expectation": "36 000–42 000 € / an",
        "contract_preference": "CDI",
        "languages": ["Français", "Anglais"],
        "source": "mock",
    },
]


def search_mock_profiles(criteria: dict, limit: int = 8) -> list[dict]:
    """Filter mock profiles based on extracted criteria."""
    results = list(MOCK_PROFILES)

    required_skills = [s.lower() for s in criteria.get("required_skills", [])]
    if required_skills:
        def skill_match_score(profile: dict) -> int:
            profile_skills = [s.lower() for s in profile.get("skills", [])]
            return sum(1 for s in required_skills if any(s in ps for ps in profile_skills))

        results.sort(key=skill_match_score, reverse=True)

    location = criteria.get("location", "").lower()
    if location and location not in ("any", "remote", ""):
        location_filtered = [p for p in results if location in p["location"].lower()]
        if location_filtered:
            results = location_filtered + [p for p in results if p not in location_filtered]

    return results[:limit]
